// export const LOGIN_REQUEST = 'LOGIN_REQUEST';
// export const LOGIN_FAILED = 'LOGIN_FAILED';

// export const LIST_REQUEST = 'LIST_REQUEST';
// export const LIST_FAILED = 'LIST_FAILED';

// export const DATE_REQUEST = 'DATE_REQUEST';
// export const NAME_REQUEST = 'NAME_REQUEST';
// export const PASS_REQUEST = 'PASS_REQUEST';
// export const SCHOOL_REQUEST = 'SCHOOL_REQUEST';
// export const SEX_REQUEST = 'SEX_REQUEST';
// export const PROFILE_REQUEST = 'PROFILE_REQUEST';

// export const LEARNING_REQUEST = 'LEARNING_REQUEST';

// export const LEARNING_FAILED = 'LEARNING_FAILED';
// export const LEARNING_RESPONSE = 'LEARNING_RESPONSE';
// export const LEARNING_ENABLE = 'LEARNING_RESPONSE';
// export const LEARNING_DISABLE = 'LEARNING_RESPONSE';

// export const YOUTUBE_REQUEST = 'YOUTUBE_REQUEST';
// export const COMMENT_REQUEST = 'COMMENT_REQUEST';
